# localization.py

LANGUAGES = {
    'it': {
        'main_menu_text': "Benvenuto! Scegli un'opzione dal menu:",
        'summarize': "Riassumi",
        'settings': "Impostazioni",
        'settings_menu_text': "Scegli un’opzione dalle impostazioni:",
        'language': "Lingua",
        'daily_summary': "Riassunto Giornaliero",
        'filter': "Filtro",
        'summary_length': "Lunghezza Riassunto",
        'language_menu_text': "Scegli la lingua preferita:",
        'summary_length_menu_text': "Imposta la lunghezza del riassunto:",
        'breve': "Breve",
        'medio': "Medio",
        'lungo': "Lungo",
        'auto_summary_menu_text': "Imposta Auto-Riassunto:",
        'summary_settings_menu_text': "Imposta le preferenze di riassunto:",
        'back': "Indietro",
        'confirmation_update': "Preferenza '{key}' aggiornata a '{value}'.",
        'error_menu_not_found': "Errore: menu non trovato.",
        'processing_summary': "Sto generando il riassunto, attendi qualche istante...",
        'help_text': "Ecco la lista dei comandi:",
        'preferences_header': "Preferenze attuali:",
        'filter_menu_text': "Configura i filtri:",
        'set_filter_placeholder': "Imposta Filtro",
        'error_invalid_format': "Errore formato non valido, Riprova.",
        'error_invalid_summary_length_format': "Errore: seleziona una lunghezza valida per il riassunto.",
    },
    'en': {
        'main_menu_text': "Welcome! Choose an option from the menu:",
        'summarize': "Summarize",
        'settings': "Settings",
        'settings_menu_text': "Choose an option from settings:",
        'language': "Language",
        'daily_summary': "Daily Summary",
        'filter': "Filter",
        'summary_length': "Summary Length",
        'language_menu_text': "Choose your preferred language:",
        'summary_length_menu_text': "Set summary length:",
        'breve': "Short",
        'medio': "Medium",
        'lungo': "Long",
        'auto_summary_menu_text': "Set Auto-Summarize:",
        'summary_settings_menu_text': "Set summary preferences:",
        'back': "Back",
        'confirmation_update': "Preference '{key}' updated to '{value}'.",
        'error_menu_not_found': "Error: menu not found.",
        'processing_summary': "Generating summary, please wait...",
        'help_text': "Here is the list of commands:",
        'preferences_header': "Current preferences:",
        'filter_menu_text': "Configure filters:",
        'set_filter_placeholder': "Set Filter",
        'error_invalid_format': "Invalid format error, please try again.",
        'error_invalid_summary_length_format': "Error: please select a valid summary length.",
    },
    'fr': {
        'main_menu_text': "Bienvenue! Choisissez une option dans le menu:",
        'summarize': "Résumé",
        'settings': "Paramètres",
        'settings_menu_text': "Choisissez une option dans les paramètres:",
        'language': "Langue",
        'daily_summary': "Résumé Quotidien",
        'filter': "Filtre",
        'summary_length': "Longueur du Résumé",
        'language_menu_text': "Choisissez votre langue préférée:",
        'summary_length_menu_text': "Définir la longueur du résumé:",
        'breve': "Court",
        'medio': "Moyen",
        'lungo': "Long",
        'auto_summary_menu_text': "Configurer le Résumé Automatique:",
        'summary_settings_menu_text': "Configurer les préférences de résumé:",
        'back': "Retour",
        'confirmation_update': "Préférence '{key}' mise à jour à '{value}'.",
        'error_menu_not_found': "Erreur : menu non trouvé.",
        'processing_summary': "Génération du résumé, veuillez patienter...",
        'help_text': "Voici la liste des commandes:",
        'preferences_header': "Préférences actuelles :",
        'filter_menu_text': "Configurer les filtres:",
        'set_filter_placeholder': "Définir le filtre",
        'error_invalid_format': "Erreur de format invalide, veuillez réessayer.",
        'error_invalid_summary_length_format': "Erreur : veuillez sélectionner une longueur de résumé valide.",
    },
}
